# Generated by Django 4.2.6 on 2023-11-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('artist', models.CharField(max_length=250, verbose_name='artist')),
                ('filepath', models.CharField(max_length=1000, verbose_name='filepath')),
            ],
            options={
                'verbose_name': 'Traks',
            },
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User'},
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Password',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Login',
        ),
        migrations.AddField(
            model_name='users',
            name='login',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='login'),
        ),
    ]
