# Generated by Django 4.2.6 on 2024-03-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('creatorid', models.IntegerField(verbose_name='CreatorId')),
                ('image', models.CharField(max_length=250, verbose_name='image_url')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('tracksid', models.CharField(max_length=250, verbose_name='tracksid')),
                ('isprivat', models.CharField(max_length=200, verbose_name='isprivat')),
            ],
            options={
                'verbose_name': 'PlayList',
            },
        ),
    ]
