# Generated by Django 4.2.6 on 2024-03-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='liked',
            field=models.IntegerField(verbose_name='liked'),
        ),
    ]
