# Generated by Django 4.2.6 on 2023-11-14 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bd', '0002_traks_alter_users_options_rename_name_users_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traks',
            options={'verbose_name': 'Trak'},
        ),
    ]
