# Generated by Django 4.2.6 on 2024-03-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bd', '0002_alter_playlist_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='liked',
            field=models.CharField(max_length=250, verbose_name='liked'),
        ),
    ]
