# Generated by Django 4.2.6 on 2023-11-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bd', '0003_alter_traks_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='traks',
            name='tags',
            field=models.CharField(max_length=1000, null=True, verbose_name='tags'),
        ),
    ]
