import os
from time import sleep

os.system("docker pull postgres")
sleep(10)
os.system("docker run --name test -p 5432:5432 -e POSTGRES_PASSWORD=0000 -d postgres")
sleep(1)
os.system("docker exec -it test psql -U postgres")
sleep(1)
os.system("CREATE DATABASE test;")
sleep(1)
os.system("CREATE USER test_user WITH PASSWORD '0000';")
sleep(1)
os.system("ALTER ROLE test_user SET client_encoding='utf8';")
sleep(1)
os.system("ALTER ROLE test_user SET default_transaction_isolation TO 'read  commited;")
sleep(1)
os.system("ALTER ROLE test_user SET timezone TO 'UTC';")
sleep(1)
os.system("ALTER DATABASE test OWNER TO test_user;")
sleep(1)
os.system("\q")
sleep(1)
os.system("python .\manage.py makemigrations")
sleep(1)
os.system("python .\manage.py migrate")